### ISSUE TITLE
From srfi/19, string->date internally fails on certain inputs

### ISSUE THREAD

**Issue by lexi-lambda** [racket/srfi#1]
Reported by Jordan Johnson via the users mailing list [here](http://lists.racket-lang.org/users/archive/2015-January/065793.html). It seems that `string->date` fails in some way when parsing certain format strings.

```racket
(require srfi/19)
(string->date "Sun, 02 Feb 2015" "~a, ~d ~b ~Y")
```

```
result arity mismatch;
expected number of values not received
 expected: 1
 received: 0
 values...:
```

**Comment by rfindler** [comment]
Thanks, I've pushed the linked commit.
