### ISSUE TITLE
 srfi-lib/srfi/32/sort.txt, srfi-doc/srfi/scribblings/srfi-{5,29}.html licensing looks incompatible with LGPL 

### ISSUE THREAD

**Issue by bremner** [racket/srfi#4]
The statement  "this document itself may not be modified in any way" seems to be incompatible with the top level LGPL license. Possibly unrelated, but I didn't find documentation for srfi/32 on docs.racket-lang.org

**Comment by bremner** [comment]
Same issue for srfi-doc/srfi/scribblings/srfi-std/srfi-29.html, srfi/scribblings/srfi-std/srfi-5.html

I'm happy to open seperate issues if that's less annoying.

**Comment by jeapostrophe** [comment]
@samth Can you weigh in on this? Can we just delete the documentation, given that it is legacy stuff? Maybe provide a link to the SRFI site so we are not distributing it? The Debian maintainers think this will block them, as well as Fedora.

**Comment by samth** [comment]
I think these are not combined with anything else in the Racket distribution, and thus we're just distributing them in a way consistent with their license. However, if people want to remove them in further distribution of Racket, that seems fine too. Do we need to remove them ourselves for that to happen?

Also, I thought srfis had a license they were supposed to follow.

**Comment by samth** [comment]
At least 32 is available under a less restrictive license here: https://srfi.schemers.org/srfi-32/srfi-32.txt

**Comment by bremner** [comment]
Jay McCarthy <notifications@github.com> writes:

> @samth Can you weigh in on this? Can we just delete the documentation, given that it is legacy stuff? Maybe provide a link to the SRFI site so we are not distributing it? The Debian maintainers think this will block them, as well as Fedora.

I wouldn't say it blocks me, just creates some inconvenience, and it
means the tarball debian distributes is not identical to the one that
PLT does, which makes e.g. tamper detection harder.

d

**Comment by jeapostrophe** [comment]
I guess, we don't need to remove them and the only downside is if the online docs disagree with local, but that happens anyways because of packages. So, I'll be closing this issue and just advising distributors that care that it is okay to delete the files as they need?

**Comment by bremner** [comment]
Jay McCarthy <notifications@github.com> writes:

> I guess, we don't need to remove them and the only downside is if the
> online docs disagree with local, but that happens anyways because of
> packages. So, I'll be closing this issue and just advising
> distributors that care that it is okay to delete the files as they
> need?
>

I guess as long as you don't want to claim that everything you
distribute is (re)-licensed under some umbrella license, distributing
those (unmodifed) files is fine.

Practically it will probably slow down the distro packaging of new
releases a bit, since it's a bit of busywork.

d

**Comment by samth** [comment]
Well, at least for srfi 32, we can just update the file to one with a
permissive license.

**Comment by samth** [comment]
So, the version in the source code for SRFI 32 is somewhat newer and in line with the source code, but I can't find the source of it at all. The source on Olin's web site, and on the SRFI site, has an earlier version of the text. I can't find the text we have anywhere on the internet.

**Comment by LiberalArtist** [comment]
@arthurgleckler As I've been working on updating Racket's copy of SRFI 29, I noticed that Racket at some point added anchors for linking to the specifications of individual identifiers, which are not present in the upstream version (and never were—I've looked through the entire Git history). For example, compare <https://github.com/racket/srfi/blob/736ae1a941e5de6decfd23fa4cdb98e4232f82a9/srfi-doc-nonfree/srfi/scribblings/srfi-std/srfi-29.html#L106> to <https://github.com/scheme-requests-for-implementation/srfi-29/blob/e39958a31c97af26f2f6a3d14fa027e09de15feb/srfi-29.html#L117>.

I want to take this opportunity to sync all of Racket's SRFI HTML documents with the vastly improved upstream markup (e.g. for <https://github.com/racket/srfi/issues/8>). I'd be happy to make pull requests to the @scheme-requests-for-implementation repositories to add any missing anchors, but I wanted to check (a) if that would be desirable and (b) if I should just do it by hand or if there are scripts I ought to use.

**Comment by arthurgleckler** [comment]
On Fri, Nov 12, 2021 at 10:28 AM Philip McGrath ***@***.***>
wrote:

> I want to take this opportunity to sync all of Racket's SRFI HTML
> documents with the vastly improved upstream markup (e.g. for #8
> <https://github.com/racket/srfi/issues/8>). I'd be happy to make pull
> requests to the @scheme-requests-for-implementation
> <https://github.com/scheme-requests-for-implementation> repositories to
> add any missing anchors, but I wanted to check (a) if that would be
> desirable and (b) if I should just do it by hand or if there are scripts I
> ought to use.
>
That would be fantastic.  I only wish there were scripts to do it!
