### ISSUE TITLE
srfi/19 not implementing any of the ISO-8601 shortcuts for `string->date`

### ISSUE THREAD

**Issue by zenspider** [racket/srfi#9]
```racket
(require srfi/19)
(string->date "2019-02-26" "~Y-~m-~d")  ; (date* 0 0 0 26 2 2019 ...)
(string->date "2019-02-26" "~1")        ; TIME-ERROR type bad-date-format-string: "~1"
```

The documentation says:

```
| ~1 | ISO-8601 year-month-day format |
...
| ~5 | ISO-8601 year-month-day-hour-minute-second format |
```

but https://github.com/racket/srfi/blob/7c1fd604cac07fb4f4a7480f4f45e1aefa78e69b/srfi-lite-lib/srfi/19/time.rkt#L1491-L1548 implements none of the numeric ISO-8601 shortcuts.

The assoc isn't exported and I'm not sure the correct process of going about testing changes on a standard racket module. Suggestions welcome.

**Comment by jbclements** [comment]
Take another look at those docs: it appears that those formatting strings (e.g. ~1) are valid for date->string, but not for string->date.

**Comment by jbclements** [comment]
Apologies if I'm misunderstanding you!

**Comment by jbclements** [comment]
Also, you might be interested in "gregor", which is being actively developed and might well support these formats.

https://pkgs.racket-lang.org/package/gregor

**Comment by jbclements** [comment]
Here's the page specifically on parsing of time/date/etc.

http://docs.racket-lang.org/gregor/time-format.html

**Comment by jbclements** [comment]
I'm closing this issue, but please feel free to re-open this if I've closed it in error.

**Comment by zenspider** [comment]
Nope! I went back and looked and agree with you. I was confused by the title of the table being below the table, not above it.
